"""add inquiries table

Revision ID: 373728dfc101
Revises: 472ad3ac5066
Create Date: 2025-11-02 03:33:36.610424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373728dfc101'
down_revision = '472ad3ac5066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('preferred_time', sa.DateTime(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_seller_id'), ['seller_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiries_seller_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_car_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_buyer_id'))

    op.drop_table('inquiries')
    # ### end Alembic commands ###
